import { storage } from "./storage";
import type { WorkOrder, LlmSettings } from "@shared/schema";
import type { Tier1Result, Tier2Result, EffectiveLlmConfig } from "./llm-client";
import {
  llmPlanSteps,
  llmExecStep,
  llmEvaluate,
  llmRefine,
  effectiveConfigToSettings,
} from "./llm-client";

function shouldBlockFallback(order: WorkOrder): { blocked: boolean; reason: string | null } {
  if (order.type === "incident" && order.priority === "critical") {
    return { blocked: true, reason: "Critical incident requires escalation — BDM marker emitted for human review." };
  }
  return { blocked: false, reason: null };
}

function generateFallbackDeliverable(order: WorkOrder): string {
  const timestamp = new Date().toISOString();
  const typeLabels: Record<string, string> = {
    deployment: "Deployment Report",
    maintenance: "Maintenance Report",
    incident: "Incident Report",
    change_request: "Change Request Summary",
    security: "Security Assessment",
    configuration: "Configuration Change Report",
    standard: "Task Completion Report",
  };
  const label = typeLabels[order.type] || "Task Completion Report";

  return `# ${label}: ${order.title}

## Objective
${order.description}

## Execution Summary
This work order was processed by Aiden's PocketFlow engine using the hardcoded policy engine (LLM not enabled). The order passed Tier 1 policy validation and was executed by the assigned sub-agent.

## Actions Taken
1. **Schema Validation** — Work order schema validated against ${order.type} requirements
2. **Policy Check** — Priority "${order.priority}" cleared all policy gates
3. **Execution** — Work order executed by handler with standard procedures
4. **Verification** — Output verified and marked as complete

## Result
Work order "${order.title}" has been completed successfully. All actions were performed according to standard operating procedures for ${order.type} work orders.

## Recommendations
- Enable LLM integration in Settings to get AI-generated deliverables with full context-aware content
- Review execution logs for detailed step-by-step timeline

---
_Generated by Aiden PocketFlow (fallback mode) on ${timestamp}_`;
}

export interface PlanStep {
  id: string;
  name: string;
  description: string;
  dependencies: string[];
  status: "pending" | "running" | "completed" | "failed" | "blocked";
  output?: string;
  error?: string;
  modelOverride?: string;
}

export interface EvaluationResult {
  score: number;
  meetsCriteria: boolean;
  gaps: string[];
  strengths: string[];
  reasoning: string;
}

export interface RefinementResult {
  gaps: string[];
  deltaSteps: PlanStep[];
  reasoning: string;
}

export interface SharedDict {
  workOrder: WorkOrder;
  tier1Result: Tier1Result;
  llmConfig: EffectiveLlmConfig | null;
  llmSettings: LlmSettings | null;

  planSteps: PlanStep[];
  currentStepIndex: number;
  accumulatedOutputs: Record<string, string>;
  stepResults: Array<{ stepId: string; stepName: string; output: string; iteration: number }>;

  iteration: number;
  maxIterations: number;
  convergenceThreshold: number;
  evaluationScore: number;
  evaluationResult: EvaluationResult | null;
  refinementHistory: Array<{ iteration: number; gaps: string[]; deltaSteps: string[] }>;

  bdmMarker: any | null;
  partialDeliverables: string[];
  blocked: boolean;

  finalDeliverable: string;
  finalMessage: string;
  deliverableType: "document" | "code" | "image" | "mixed";
  deliverableTitle: string;

  logs: Array<{ node: string; message: string; metadata?: any }>;
}

type NodeAction = "continue" | "bdm" | "done" | "more_steps" | "converged" | "refine" | "best_effort";

interface NodeResult {
  action: NodeAction;
  error?: string;
}

function createSharedDict(
  order: WorkOrder,
  tier1Result: Tier1Result,
  llmConfig: EffectiveLlmConfig | null,
  settings: LlmSettings | null,
  maxIterations: number = 3,
  convergenceThreshold: number = 0.8
): SharedDict {
  return {
    workOrder: order,
    tier1Result,
    llmConfig,
    llmSettings: settings,
    planSteps: [],
    currentStepIndex: 0,
    accumulatedOutputs: {},
    stepResults: [],
    iteration: 0,
    maxIterations,
    convergenceThreshold,
    evaluationScore: 0,
    evaluationResult: null,
    refinementHistory: [],
    bdmMarker: null,
    partialDeliverables: [],
    blocked: false,
    finalDeliverable: "",
    finalMessage: "",
    deliverableType: "document",
    deliverableTitle: "",
    logs: [],
  };
}

function addLog(dict: SharedDict, node: string, message: string, metadata?: any) {
  dict.logs.push({ node, message, metadata });
}

async function emitNodeLog(dict: SharedDict, node: string, message: string, metadata?: any) {
  addLog(dict, node, message, metadata);
  if (dict.workOrder.id) {
    await storage.createExecutionLog({
      workOrderId: dict.workOrder.id,
      tier: 2,
      action: `PocketFlow: ${node}`,
      message,
      metadata: { ...metadata, iteration: dict.iteration, node },
    });
  }
}

function getEffectiveSettings(dict: SharedDict): LlmSettings | null {
  if (dict.llmConfig) return effectiveConfigToSettings(dict.llmConfig);
  return dict.llmSettings;
}

function getEffectiveApiKey(dict: SharedDict): string | undefined {
  return dict.llmConfig?.directApiKey || (dict.llmConfig ? dict.llmConfig.apiKeyEnvVar : undefined);
}

function getSystemPrompt(dict: SharedDict): string {
  return dict.llmConfig?.systemPrompt || dict.llmSettings?.systemPrompt || "";
}

async function nodeValidateWorkOrder(dict: SharedDict): Promise<NodeResult> {
  const order = dict.workOrder;

  if (!order.title || !order.description) {
    dict.blocked = true;
    dict.bdmMarker = {
      type: "validation_failure",
      reason: "Work order missing required fields (title or description)",
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    await emitNodeLog(dict, "ValidateWorkOrder", `Validation failed: missing required fields`, { blocked: true });
    return { action: "bdm" };
  }

  if (!order.type || !order.priority) {
    dict.blocked = true;
    dict.bdmMarker = {
      type: "validation_failure",
      reason: "Work order missing type or priority classification",
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    await emitNodeLog(dict, "ValidateWorkOrder", `Validation failed: missing type/priority`, { blocked: true });
    return { action: "bdm" };
  }

  const fallbackBlock = shouldBlockFallback(order);
  if (fallbackBlock.blocked) {
    dict.blocked = true;
    dict.bdmMarker = {
      type: "policy_block",
      reason: fallbackBlock.reason,
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    await emitNodeLog(dict, "ValidateWorkOrder", `Blocked by policy rule: ${fallbackBlock.reason}`, { blocked: true });
    return { action: "bdm" };
  }

  await emitNodeLog(dict, "ValidateWorkOrder", `Schema validated for "${order.title}" (${order.type}/${order.priority})`, {
    valid: true,
    title: order.title,
    type: order.type,
    priority: order.priority,
  });

  return { action: "continue" };
}

async function nodePlanSteps(dict: SharedDict): Promise<NodeResult> {
  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);

  const isRefinement = dict.iteration > 0;
  const existingGaps = dict.evaluationResult?.gaps || [];
  const existingOutputs = dict.accumulatedOutputs;

  if (!settings) {
    const singleStep: PlanStep = {
      id: "step_fallback",
      name: "Execute Work Order (Fallback)",
      description: `Process "${dict.workOrder.title}" using hardcoded policy engine`,
      dependencies: [],
      status: "pending",
    };
    dict.planSteps = [singleStep];
    dict.currentStepIndex = 0;
    await emitNodeLog(dict, "PlanSteps", `Fallback mode: single-step plan created (no LLM)`, { stepCount: 1, fallback: true });
    return { action: "continue" };
  }

  try {
    const planned = await llmPlanSteps(
      settings,
      systemPrompt,
      dict.workOrder,
      dict.tier1Result,
      isRefinement ? existingGaps : [],
      isRefinement ? existingOutputs : {},
      apiKey
    );

    if (isRefinement) {
      for (const newStep of planned) {
        const existing = dict.planSteps.find(s => s.id === newStep.id);
        if (!existing) {
          dict.planSteps.push({ ...newStep, status: "pending" });
        }
      }
      dict.currentStepIndex = dict.planSteps.findIndex(s => s.status === "pending");
      if (dict.currentStepIndex === -1) dict.currentStepIndex = 0;
    } else {
      dict.planSteps = planned.map(s => ({ ...s, status: "pending" as const }));
      dict.currentStepIndex = 0;
    }

    await emitNodeLog(dict, "PlanSteps",
      isRefinement
        ? `Delta refinement: ${planned.length} new/updated steps added (iteration ${dict.iteration})`
        : `Plan created: ${dict.planSteps.length} steps`,
      {
        stepCount: dict.planSteps.length,
        isRefinement,
        gaps: existingGaps,
        steps: dict.planSteps.map(s => ({ id: s.id, name: s.name, deps: s.dependencies })),
      }
    );

    return { action: "continue" };
  } catch (err: any) {
    const singleStep: PlanStep = {
      id: "step_1",
      name: "Execute Work Order",
      description: `Process "${dict.workOrder.title}" — ${dict.workOrder.description}`,
      dependencies: [],
      status: "pending",
    };
    dict.planSteps = [singleStep];
    dict.currentStepIndex = 0;
    await emitNodeLog(dict, "PlanSteps", `LLM planning failed, using single-step fallback: ${err.message}`, { error: err.message });
    return { action: "continue" };
  }
}

function getReadySteps(dict: SharedDict): PlanStep[] {
  return dict.planSteps.filter(step => {
    if (step.status !== "pending") return false;
    return step.dependencies.every(depId => {
      const dep = dict.planSteps.find(s => s.id === depId);
      return dep && dep.status === "completed";
    });
  });
}

function cascadeFailBlockedDeps(dict: SharedDict): PlanStep[] {
  const cascaded: PlanStep[] = [];
  let changed = true;
  while (changed) {
    changed = false;
    for (const step of dict.planSteps) {
      if (step.status !== "pending") continue;
      const hasFailedDep = step.dependencies.some(depId => {
        const dep = dict.planSteps.find(s => s.id === depId);
        return dep && (dep.status === "failed" || dep.status === "blocked");
      });
      if (hasFailedDep) {
        step.status = "failed";
        step.error = "Dependency failed — cascaded failure";
        cascaded.push(step);
        changed = true;
      }
    }
  }
  return cascaded;
}

async function nodeExecStep(dict: SharedDict): Promise<NodeResult> {
  const readySteps = getReadySteps(dict);

  if (readySteps.length === 0) {
    const hasBlocked = dict.planSteps.some(s => s.status === "blocked");
    if (hasBlocked) return { action: "bdm" };

    const allDone = dict.planSteps.every(s => s.status === "completed" || s.status === "failed");
    if (allDone) return { action: "done" };

    const cascaded = cascadeFailBlockedDeps(dict);
    if (cascaded.length > 0) {
      await emitNodeLog(dict, "ExecStep",
        `Cascade-failed ${cascaded.length} step(s) due to failed dependencies: ${cascaded.map(s => s.name).join(", ")}`,
        { cascadedSteps: cascaded.map(s => ({ id: s.id, name: s.name })) }
      );
      const allDoneNow = dict.planSteps.every(s => s.status === "completed" || s.status === "failed");
      if (allDoneNow) return { action: "done" };
      return { action: "more_steps" };
    }

    dict.blocked = true;
    dict.bdmMarker = {
      type: "execution_deadlock",
      reason: "No executable steps and not all steps complete — possible dependency deadlock",
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    return { action: "bdm" };
  }

  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);

  const executeStep = async (step: PlanStep): Promise<void> => {
    step.status = "running";

    await emitNodeLog(dict, "ExecStep", `Executing step "${step.name}"`, {
      stepId: step.id,
      stepName: step.name,
      parallel: readySteps.length > 1,
    });

    try {
      if (!settings) {
        step.output = generateFallbackDeliverable(dict.workOrder);
      } else {
        const result = await llmExecStep(
          settings,
          systemPrompt,
          dict.workOrder,
          step,
          dict.accumulatedOutputs,
          apiKey
        );

        if (result.blocked) {
          step.status = "blocked";
          step.error = result.reason || "Step blocked";
          dict.partialDeliverables.push(...Object.values(dict.accumulatedOutputs));
          dict.bdmMarker = {
            type: "step_block",
            reason: result.reason,
            stepId: step.id,
            stepName: step.name,
            tier: 2,
            timestamp: new Date().toISOString(),
          };
          await emitNodeLog(dict, "ExecStep", `Step "${step.name}" blocked: ${result.reason}`, {
            stepId: step.id,
            blocked: true,
          });
          return;
        }

        step.output = result.output || "";
      }

      step.status = "completed";
      dict.accumulatedOutputs[step.id] = step.output || "";
      dict.stepResults.push({
        stepId: step.id,
        stepName: step.name,
        output: step.output || "",
        iteration: dict.iteration,
      });

      await emitNodeLog(dict, "ExecStep", `Step "${step.name}" completed`, {
        stepId: step.id,
        outputLength: (step.output || "").length,
      });
    } catch (err: any) {
      step.status = "failed";
      step.error = err.message;
      await emitNodeLog(dict, "ExecStep", `Step "${step.name}" failed: ${err.message}`, {
        stepId: step.id,
        error: err.message,
      });
    }
  };

  if (readySteps.length > 1) {
    await emitNodeLog(dict, "ExecStep", `Parallel execution: ${readySteps.length} independent steps`, {
      steps: readySteps.map(s => s.name),
    });
    await Promise.all(readySteps.map(step => executeStep(step)));
  } else {
    await executeStep(readySteps[0]);
  }

  const hasBlocked = dict.planSteps.some(s => s.status === "blocked");
  if (hasBlocked) {
    dict.blocked = true;
    return { action: "bdm" };
  }

  const hasMorePending = dict.planSteps.some(s => s.status === "pending");
  if (hasMorePending) return { action: "more_steps" };

  return { action: "done" };
}

async function nodeEmitBDM(dict: SharedDict): Promise<NodeResult> {
  const partialOutput = Object.values(dict.accumulatedOutputs).join("\n\n---\n\n");
  dict.partialDeliverables = partialOutput ? [partialOutput] : [];

  await emitNodeLog(dict, "EmitBDM", `BDM marker emitted: ${dict.bdmMarker?.reason || "Unknown block"}`, {
    bdmMarker: dict.bdmMarker,
    partialOutputKeys: Object.keys(dict.accumulatedOutputs),
    iteration: dict.iteration,
  });

  return { action: "done" };
}

async function nodeEvaluate(dict: SharedDict): Promise<NodeResult> {
  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);
  const combinedOutput = Object.values(dict.accumulatedOutputs).join("\n\n");

  const failedSteps = dict.planSteps.filter(s => s.status === "failed");
  if (failedSteps.length > 0 && dict.iteration < dict.maxIterations - 1) {
    const failedGaps = failedSteps.map(s => `Step "${s.name}" failed: ${s.error || "unknown error"}`);
    dict.evaluationScore = 0.4;
    dict.evaluationResult = {
      score: 0.4,
      meetsCriteria: false,
      gaps: failedGaps,
      strengths: dict.planSteps.filter(s => s.status === "completed").map(s => `Step "${s.name}" completed`),
      reasoning: `${failedSteps.length} step(s) failed — triggering refinement`,
    };
    await emitNodeLog(dict, "Evaluate", `${failedSteps.length} failed steps detected — forcing refinement`, {
      failedSteps: failedSteps.map(s => s.name),
      score: 0.4,
    });
    return { action: "refine" };
  }

  const completedSteps = dict.planSteps.filter(s => s.status === "completed");
  const allFailed = completedSteps.length === 0 && dict.planSteps.length > 0;

  if (allFailed) {
    dict.evaluationScore = 0.0;
    dict.evaluationResult = {
      score: 0.0,
      meetsCriteria: false,
      gaps: dict.planSteps.map(s => `Step "${s.name}" ${s.status}: ${s.error || "no output"}`),
      strengths: [],
      reasoning: "All steps failed — no deliverable produced",
    };
    await emitNodeLog(dict, "Evaluate", `All ${dict.planSteps.length} steps failed — best effort with empty output`, {
      score: 0.0,
      failedCount: dict.planSteps.length,
    });
    return { action: "best_effort" };
  }

  if (!settings || !combinedOutput) {
    dict.evaluationScore = 1.0;
    dict.evaluationResult = {
      score: 1.0,
      meetsCriteria: true,
      gaps: [],
      strengths: ["Execution completed"],
      reasoning: "Fallback mode — no evaluation needed",
    };
    await emitNodeLog(dict, "Evaluate", `Fallback mode: auto-converged (score=1.0)`, { score: 1.0 });
    return { action: "converged" };
  }

  try {
    const evalResult = await llmEvaluate(
      settings,
      systemPrompt,
      dict.workOrder,
      combinedOutput,
      dict.planSteps,
      apiKey
    );

    dict.evaluationScore = evalResult.score;
    dict.evaluationResult = evalResult;

    await emitNodeLog(dict, "Evaluate",
      `Quality score: ${evalResult.score.toFixed(2)} | Criteria met: ${evalResult.meetsCriteria} | Gaps: ${evalResult.gaps.length}`,
      { ...evalResult, iteration: dict.iteration }
    );

    if (evalResult.score >= dict.convergenceThreshold && evalResult.meetsCriteria) {
      return { action: "converged" };
    }

    if (dict.iteration >= dict.maxIterations - 1) {
      await emitNodeLog(dict, "Evaluate", `Max iterations (${dict.maxIterations}) reached — delivering best effort`, {
        score: evalResult.score,
      });
      return { action: "best_effort" };
    }

    return { action: "refine" };
  } catch (err: any) {
    dict.evaluationScore = 0.85;
    dict.evaluationResult = {
      score: 0.85,
      meetsCriteria: true,
      gaps: [],
      strengths: ["Execution completed"],
      reasoning: `Evaluation LLM failed (${err.message}), assuming acceptable quality`,
    };
    await emitNodeLog(dict, "Evaluate", `Evaluation LLM failed, auto-converging: ${err.message}`, { error: err.message });
    return { action: "converged" };
  }
}

async function nodeRefine(dict: SharedDict): Promise<NodeResult> {
  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);
  const gaps = dict.evaluationResult?.gaps || [];

  if (!settings || gaps.length === 0) {
    await emitNodeLog(dict, "Refine", `No refinable gaps — converging`, { gaps: [] });
    return { action: "converged" };
  }

  try {
    const refinement = await llmRefine(
      settings,
      systemPrompt,
      dict.workOrder,
      gaps,
      dict.accumulatedOutputs,
      dict.planSteps,
      apiKey
    );

    dict.refinementHistory.push({
      iteration: dict.iteration,
      gaps: refinement.gaps,
      deltaSteps: refinement.deltaSteps.map(s => s.name),
    });

    for (const step of dict.planSteps) {
      if (step.status === "failed") {
        step.status = "pending";
        step.error = undefined;
      }
    }

    dict.iteration++;

    await emitNodeLog(dict, "Refine",
      `Refinement iteration ${dict.iteration}: ${refinement.deltaSteps.length} delta steps identified`,
      { gaps: refinement.gaps, deltaSteps: refinement.deltaSteps.map(s => s.name) }
    );

    return { action: "continue" };
  } catch (err: any) {
    await emitNodeLog(dict, "Refine", `Refinement LLM failed, converging with current output: ${err.message}`, { error: err.message });
    return { action: "converged" };
  }
}

async function nodeBuildResponse(dict: SharedDict): Promise<NodeResult> {
  const allOutputs = Object.values(dict.accumulatedOutputs);
  let combinedDeliverable = allOutputs.join("\n\n");

  if (!combinedDeliverable.trim() && dict.stepResults.length === 0) {
    combinedDeliverable = generateFallbackDeliverable(dict.workOrder);
  }

  const typeToDeliverableType: Record<string, "document" | "code" | "image" | "mixed"> = {
    deployment: "document",
    maintenance: "document",
    incident: "document",
    change_request: "document",
    security: "document",
    configuration: "code",
    standard: "document",
  };

  dict.finalDeliverable = combinedDeliverable;
  dict.finalMessage = `Work order "${dict.workOrder.title}" processed successfully.`;
  let detectedType = typeToDeliverableType[dict.workOrder.type] || "document";
  const codeBlockMatches = combinedDeliverable.match(/```(html|javascript|js|css)\b[\s\S]*?```/gi) || [];
  const totalCodeLength = codeBlockMatches.reduce((sum, m) => sum + m.length, 0);
  if (totalCodeLength > 200 || /<!DOCTYPE\s+html|<html[\s>]/i.test(combinedDeliverable)) {
    detectedType = "code";
  }
  dict.deliverableType = detectedType;
  dict.deliverableTitle = dict.workOrder.title;

  if (dict.stepResults.length > 0) {
    const lastResult = dict.stepResults[dict.stepResults.length - 1];
    if (lastResult.output) {
      dict.finalDeliverable = combinedDeliverable;
    }
  }

  await emitNodeLog(dict, "BuildResponse",
    `Final deliverable assembled | Score: ${dict.evaluationScore.toFixed(2)} | Iterations: ${dict.iteration + 1} | Steps: ${dict.stepResults.length}`,
    {
      score: dict.evaluationScore,
      iterations: dict.iteration + 1,
      totalSteps: dict.stepResults.length,
      deliverableLength: dict.finalDeliverable.length,
      deliverableType: dict.deliverableType,
    }
  );

  return { action: "done" };
}

export async function pocketflowExecute(
  order: WorkOrder,
  tier1Result: Tier1Result,
  llmConfig: EffectiveLlmConfig | null,
  settings: LlmSettings | null,
  options?: { maxIterations?: number; convergenceThreshold?: number }
): Promise<Tier2Result> {
  const dict = createSharedDict(
    order,
    tier1Result,
    llmConfig,
    settings,
    options?.maxIterations ?? 3,
    options?.convergenceThreshold ?? 0.8
  );

  await emitNodeLog(dict, "PocketFlow", `Starting iterative execution for "${order.title}"`, {
    maxIterations: dict.maxIterations,
    convergenceThreshold: dict.convergenceThreshold,
    hasLLM: !!llmConfig || !!settings?.enabled,
  });

  const validateResult = await nodeValidateWorkOrder(dict);
  if (validateResult.action === "bdm") {
    await nodeEmitBDM(dict);
    return buildBlockedResult(dict);
  }

  const planResult = await nodePlanSteps(dict);
  if (planResult.action === "bdm") {
    await nodeEmitBDM(dict);
    return buildBlockedResult(dict);
  }

  while (dict.iteration < dict.maxIterations) {
    let execAction: NodeAction = "more_steps";
    while (execAction === "more_steps") {
      const execResult = await nodeExecStep(dict);
      execAction = execResult.action;

      if (execAction === "bdm") {
        await nodeEmitBDM(dict);
        return buildBlockedResult(dict);
      }
    }

    const evalResult = await nodeEvaluate(dict);

    if (evalResult.action === "converged" || evalResult.action === "best_effort") {
      await nodeBuildResponse(dict);
      return buildSuccessResult(dict);
    }

    if (evalResult.action === "refine") {
      const refineResult = await nodeRefine(dict);
      if (refineResult.action === "converged") {
        await nodeBuildResponse(dict);
        return buildSuccessResult(dict);
      }

      const rePlanResult = await nodePlanSteps(dict);
      if (rePlanResult.action === "bdm") {
        await nodeEmitBDM(dict);
        return buildBlockedResult(dict);
      }
    }
  }

  await emitNodeLog(dict, "PocketFlow", `Iteration limit reached — delivering best effort`, {
    iterations: dict.iteration,
    score: dict.evaluationScore,
  });
  await nodeBuildResponse(dict);
  return buildSuccessResult(dict);
}

function buildBlockedResult(dict: SharedDict): Tier2Result {
  const partialOutput = dict.partialDeliverables.length > 0
    ? dict.partialDeliverables.join("\n\n---\n\n")
    : undefined;

  return {
    blocked: true,
    reason: dict.bdmMarker?.reason || "Execution blocked",
    executionId: null,
    handler: dict.tier1Result.handler,
    output: partialOutput ? {
      message: "Partial output available before block",
      deliverable: partialOutput,
      deliverableType: "document",
      deliverableTitle: `${dict.workOrder.title} (partial)`,
    } : undefined,
    pocketflow: {
      iterations: dict.iteration + 1,
      convergenceScore: dict.evaluationScore,
      stepResults: dict.stepResults,
      refinementHistory: dict.refinementHistory,
      bdmMarker: dict.bdmMarker,
    },
  };
}

function buildSuccessResult(dict: SharedDict): Tier2Result {
  return {
    blocked: false,
    reason: null,
    executionId: `exec_${Date.now()}`,
    handler: dict.tier1Result.handler,
    output: {
      message: dict.finalMessage,
      deliverable: dict.finalDeliverable,
      deliverableType: dict.deliverableType,
      deliverableTitle: dict.deliverableTitle,
    },
    pocketflow: {
      iterations: dict.iteration + 1,
      convergenceScore: dict.evaluationScore,
      stepResults: dict.stepResults,
      refinementHistory: dict.refinementHistory,
    },
  };
}
