import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import { storage } from "./storage";
import type { WorkOrder, LlmSettings } from "@shared/schema";
import type { Tier1Result, Tier2Result, EffectiveLlmConfig } from "./llm-client";
import {
  llmPlanSteps,
  llmExecStep,
  llmEvaluate,
  llmRefine,
  effectiveConfigToSettings,
} from "./llm-client";
import { executeTool, getAvailableToolsForAgent, type ToolExecResult, type AvailableTool } from "./tool-executor";

function shouldBlockFallback(order: WorkOrder): { blocked: boolean; reason: string | null } {
  if (order.type === "incident" && order.priority === "critical") {
    return { blocked: true, reason: "Critical incident requires escalation — BDM marker emitted for human review." };
  }
  return { blocked: false, reason: null };
}

function generateFallbackDeliverable(order: WorkOrder): string {
  const timestamp = new Date().toISOString();
  const typeLabels: Record<string, string> = {
    deployment: "Deployment Report",
    maintenance: "Maintenance Report",
    incident: "Incident Report",
    change_request: "Change Request Summary",
    security: "Security Assessment",
    configuration: "Configuration Change Report",
    standard: "Task Completion Report",
  };
  const label = typeLabels[order.type] || "Task Completion Report";

  return `# ${label}: ${order.title}

## Objective
${order.description}

## Execution Summary
This work order was processed by Aiden's PocketFlow engine using the hardcoded policy engine (LLM not enabled). The order passed Tier 1 policy validation and was executed by the assigned sub-agent.

## Actions Taken
1. **Schema Validation** — Work order schema validated against ${order.type} requirements
2. **Policy Check** — Priority "${order.priority}" cleared all policy gates
3. **Execution** — Work order executed by handler with standard procedures
4. **Verification** — Output verified and marked as complete

## Result
Work order "${order.title}" has been completed successfully. All actions were performed according to standard operating procedures for ${order.type} work orders.

## Recommendations
- Enable LLM integration in Settings to get AI-generated deliverables with full context-aware content
- Review execution logs for detailed step-by-step timeline

---
_Generated by Aiden PocketFlow (fallback mode) on ${timestamp}_`;
}

export interface PlanStep {
  id: string;
  name: string;
  description: string;
  dependencies: string[];
  status: "pending" | "running" | "completed" | "failed" | "blocked";
  output?: string;
  error?: string;
  modelOverride?: string;
}

export interface EvaluationResult {
  score: number;
  meetsCriteria: boolean;
  gaps: string[];
  strengths: string[];
  reasoning: string;
}

export interface RefinementResult {
  gaps: string[];
  deltaSteps: PlanStep[];
  reasoning: string;
}

export interface SharedDict {
  workOrder: WorkOrder;
  tier1Result: Tier1Result;
  llmConfig: EffectiveLlmConfig | null;
  llmSettings: LlmSettings | null;

  planSteps: PlanStep[];
  currentStepIndex: number;
  accumulatedOutputs: Record<string, string>;
  stepResults: Array<{ stepId: string; stepName: string; output: string; iteration: number }>;

  iteration: number;
  maxIterations: number;
  convergenceThreshold: number;
  evaluationScore: number;
  evaluationResult: EvaluationResult | null;
  refinementHistory: Array<{ iteration: number; gaps: string[]; deltaSteps: string[] }>;

  bdmMarker: any | null;
  partialDeliverables: string[];
  blocked: boolean;

  finalDeliverable: string;
  finalMessage: string;
  deliverableType: "document" | "code" | "image" | "mixed";
  deliverableTitle: string;
  postProcessedFile: { path: string; mimeType: string; size: number } | null;

  revisionContext?: string;
  availableTools: AvailableTool[];
  toolResults: ToolExecResult[];
  logs: Array<{ node: string; message: string; metadata?: any }>;
}

type NodeAction = "continue" | "bdm" | "done" | "more_steps" | "converged" | "refine" | "best_effort";

interface NodeResult {
  action: NodeAction;
  error?: string;
}

function createSharedDict(
  order: WorkOrder,
  tier1Result: Tier1Result,
  llmConfig: EffectiveLlmConfig | null,
  settings: LlmSettings | null,
  maxIterations: number = 3,
  convergenceThreshold: number = 0.8
): SharedDict {
  return {
    workOrder: order,
    tier1Result,
    llmConfig,
    llmSettings: settings,
    planSteps: [],
    currentStepIndex: 0,
    accumulatedOutputs: {},
    stepResults: [],
    iteration: 0,
    maxIterations,
    convergenceThreshold,
    evaluationScore: 0,
    evaluationResult: null,
    refinementHistory: [],
    bdmMarker: null,
    partialDeliverables: [],
    blocked: false,
    finalDeliverable: "",
    finalMessage: "",
    deliverableType: "document",
    deliverableTitle: "",
    postProcessedFile: null,
    availableTools: [],
    toolResults: [],
    logs: [],
  };
}

function addLog(dict: SharedDict, node: string, message: string, metadata?: any) {
  dict.logs.push({ node, message, metadata });
}

async function emitNodeLog(dict: SharedDict, node: string, message: string, metadata?: any) {
  addLog(dict, node, message, metadata);
  if (dict.workOrder.id) {
    await storage.createExecutionLog({
      workOrderId: dict.workOrder.id,
      tier: 2,
      action: `PocketFlow: ${node}`,
      message,
      metadata: { ...metadata, iteration: dict.iteration, node },
    });
  }
}

function getEffectiveSettings(dict: SharedDict): LlmSettings | null {
  if (dict.llmConfig) return effectiveConfigToSettings(dict.llmConfig);
  return dict.llmSettings;
}

function getEffectiveApiKey(dict: SharedDict): string | undefined {
  return dict.llmConfig?.directApiKey || (dict.llmConfig ? dict.llmConfig.apiKeyEnvVar : undefined);
}

function getSystemPrompt(dict: SharedDict): string {
  const base = dict.llmConfig?.systemPrompt || dict.llmSettings?.systemPrompt || "";

  // Inject skill content from prompt_injection tools into system prompt
  const injectedSkills = (dict.availableTools || [])
    .filter(t => t.executionMode === "prompt_injection" && t.skillContent)
    .map(t => `\n\n---\n## Skill: ${t.name}\n${t.skillContent}`)
    .join("");

  if (!injectedSkills) return base;

  return base + "\n\n# LOADED SKILLS\nThe following skills have been loaded into your context. Use their instructions when the work order requires their capabilities." + injectedSkills;
}

async function nodeValidateWorkOrder(dict: SharedDict): Promise<NodeResult> {
  const order = dict.workOrder;

  if (!order.title || !order.description) {
    dict.blocked = true;
    dict.bdmMarker = {
      type: "validation_failure",
      reason: "Work order missing required fields (title or description)",
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    await emitNodeLog(dict, "ValidateWorkOrder", `Validation failed: missing required fields`, { blocked: true });
    return { action: "bdm" };
  }

  if (!order.type || !order.priority) {
    dict.blocked = true;
    dict.bdmMarker = {
      type: "validation_failure",
      reason: "Work order missing type or priority classification",
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    await emitNodeLog(dict, "ValidateWorkOrder", `Validation failed: missing type/priority`, { blocked: true });
    return { action: "bdm" };
  }

  const fallbackBlock = shouldBlockFallback(order);
  if (fallbackBlock.blocked) {
    dict.blocked = true;
    dict.bdmMarker = {
      type: "policy_block",
      reason: fallbackBlock.reason,
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    await emitNodeLog(dict, "ValidateWorkOrder", `Blocked by policy rule: ${fallbackBlock.reason}`, { blocked: true });
    return { action: "bdm" };
  }

  await emitNodeLog(dict, "ValidateWorkOrder", `Schema validated for "${order.title}" (${order.type}/${order.priority})`, {
    valid: true,
    title: order.title,
    type: order.type,
    priority: order.priority,
  });

  return { action: "continue" };
}

async function nodePlanSteps(dict: SharedDict): Promise<NodeResult> {
  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);

  const isRefinement = dict.iteration > 0;
  const existingGaps = dict.evaluationResult?.gaps || [];
  const existingOutputs = dict.accumulatedOutputs;

  if (!settings) {
    const singleStep: PlanStep = {
      id: "step_fallback",
      name: "Execute Work Order (Fallback)",
      description: `Process "${dict.workOrder.title}" using hardcoded policy engine`,
      dependencies: [],
      status: "pending",
    };
    dict.planSteps = [singleStep];
    dict.currentStepIndex = 0;
    await emitNodeLog(dict, "PlanSteps", `Fallback mode: single-step plan created (no LLM)`, { stepCount: 1, fallback: true });
    return { action: "continue" };
  }

  try {
    const planned = await llmPlanSteps(
      settings,
      systemPrompt,
      dict.workOrder,
      dict.tier1Result,
      isRefinement ? existingGaps : [],
      isRefinement ? existingOutputs : {},
      apiKey,
      dict.availableTools,
      dict.revisionContext
    );

    if (isRefinement) {
      for (const newStep of planned) {
        const existing = dict.planSteps.find(s => s.id === newStep.id);
        if (!existing) {
          dict.planSteps.push({ ...newStep, status: "pending" });
        }
      }
      dict.currentStepIndex = dict.planSteps.findIndex(s => s.status === "pending");
      if (dict.currentStepIndex === -1) dict.currentStepIndex = 0;
    } else {
      const rawSteps = planned.map(s => ({ ...s, status: "pending" as const }));
      // Sanitize: remove dependency IDs that don't reference any step in this plan.
      // LLMs sometimes hallucinate dep IDs (wrong names, extra steps) causing deadlocks.
      const stepIds = new Set(rawSteps.map(s => s.id));
      dict.planSteps = rawSteps.map(s => ({
        ...s,
        dependencies: s.dependencies.filter(depId => stepIds.has(depId)),
      }));
      dict.currentStepIndex = 0;
    }

    await emitNodeLog(dict, "PlanSteps",
      isRefinement
        ? `Delta refinement: ${planned.length} new/updated steps added (iteration ${dict.iteration})`
        : `Plan created: ${dict.planSteps.length} steps`,
      {
        stepCount: dict.planSteps.length,
        isRefinement,
        gaps: existingGaps,
        steps: dict.planSteps.map(s => ({ id: s.id, name: s.name, deps: s.dependencies })),
      }
    );

    return { action: "continue" };
  } catch (err: any) {
    const singleStep: PlanStep = {
      id: "step_1",
      name: "Execute Work Order",
      description: `Process "${dict.workOrder.title}" — ${dict.workOrder.description}`,
      dependencies: [],
      status: "pending",
    };
    dict.planSteps = [singleStep];
    dict.currentStepIndex = 0;
    await emitNodeLog(dict, "PlanSteps", `LLM planning failed, using single-step fallback: ${err.message}`, { error: err.message });
    return { action: "continue" };
  }
}

function getReadySteps(dict: SharedDict): PlanStep[] {
  return dict.planSteps.filter(step => {
    if (step.status !== "pending") return false;
    return step.dependencies.every(depId => {
      const dep = dict.planSteps.find(s => s.id === depId);
      // If dep ID doesn't exist in the plan (hallucinated/stale), treat as satisfied.
      return !dep || dep.status === "completed";
    });
  });
}

function cascadeFailBlockedDeps(dict: SharedDict): PlanStep[] {
  const cascaded: PlanStep[] = [];
  let changed = true;
  while (changed) {
    changed = false;
    for (const step of dict.planSteps) {
      if (step.status !== "pending") continue;
      const hasFailedDep = step.dependencies.some(depId => {
        const dep = dict.planSteps.find(s => s.id === depId);
        return dep && (dep.status === "failed" || dep.status === "blocked");
      });
      if (hasFailedDep) {
        step.status = "failed";
        step.error = "Dependency failed — cascaded failure";
        cascaded.push(step);
        changed = true;
      }
    }
  }
  return cascaded;
}

async function nodeExecStep(dict: SharedDict): Promise<NodeResult> {
  const readySteps = getReadySteps(dict);

  if (readySteps.length === 0) {
    const hasBlocked = dict.planSteps.some(s => s.status === "blocked");
    if (hasBlocked) return { action: "bdm" };

    const allDone = dict.planSteps.every(s => s.status === "completed" || s.status === "failed");
    if (allDone) return { action: "done" };

    const cascaded = cascadeFailBlockedDeps(dict);
    if (cascaded.length > 0) {
      await emitNodeLog(dict, "ExecStep",
        `Cascade-failed ${cascaded.length} step(s) due to failed dependencies: ${cascaded.map(s => s.name).join(", ")}`,
        { cascadedSteps: cascaded.map(s => ({ id: s.id, name: s.name })) }
      );
      const allDoneNow = dict.planSteps.every(s => s.status === "completed" || s.status === "failed");
      if (allDoneNow) return { action: "done" };
      return { action: "more_steps" };
    }

    dict.blocked = true;
    dict.bdmMarker = {
      type: "execution_deadlock",
      reason: "No executable steps and not all steps complete — possible dependency deadlock",
      tier: 2,
      timestamp: new Date().toISOString(),
    };
    return { action: "bdm" };
  }

  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);

  const executeStep = async (step: PlanStep): Promise<void> => {
    step.status = "running";

    await emitNodeLog(dict, "ExecStep", `Executing step "${step.name}"`, {
      stepId: step.id,
      stepName: step.name,
      parallel: readySteps.length > 1,
      availableTools: dict.availableTools.map(t => t.slug),
    });

    try {
      if (!settings) {
        step.output = generateFallbackDeliverable(dict.workOrder);
      } else {
        const result = await llmExecStep(
          settings,
          systemPrompt,
          dict.workOrder,
          step,
          dict.accumulatedOutputs,
          apiKey,
          dict.availableTools,
          dict.revisionContext
        );

        if (result.blocked) {
          step.status = "blocked";
          step.error = result.reason || "Step blocked";
          dict.partialDeliverables.push(...Object.values(dict.accumulatedOutputs));
          dict.bdmMarker = {
            type: "step_block",
            reason: result.reason,
            stepId: step.id,
            stepName: step.name,
            tier: 2,
            timestamp: new Date().toISOString(),
          };
          await emitNodeLog(dict, "ExecStep", `Step "${step.name}" blocked: ${result.reason}`, {
            stepId: step.id,
            blocked: true,
          });
          return;
        }

        step.output = result.output || "";

        if (result.toolCalls && result.toolCalls.length > 0) {
          for (const tc of result.toolCalls) {
            await emitNodeLog(dict, "ToolCall", `Executing tool "${tc.toolSlug}" with input: ${tc.input.slice(0, 100)}`, {
              stepId: step.id,
              toolSlug: tc.toolSlug,
            });

            const agentId = dict.workOrder.assignedSubAgentId || "aiden-tier2";
            const toolResult = await executeTool(tc.toolSlug, tc.input, agentId, dict.workOrder.id);
            dict.toolResults.push(toolResult);

            if (toolResult.success) {
              await emitNodeLog(dict, "ToolCall", `Tool "${toolResult.toolName}" returned ${toolResult.output.length} chars in ${toolResult.durationMs}ms`, {
                stepId: step.id,
                toolSlug: tc.toolSlug,
                leaseId: toolResult.leaseId,
                durationMs: toolResult.durationMs,
              });

              const toolOutputSection = `\n\n---\n### Tool Result: ${toolResult.toolName}\n${toolResult.output}`;
              const combinedOutput = (step.output || "") + toolOutputSection;

              if (settings) {
                try {
                  const synthesisResult = await llmExecStep(
                    settings,
                    systemPrompt,
                    dict.workOrder,
                    { ...step, description: `${step.description}\n\nTool "${toolResult.toolName}" returned the following data. Synthesize it into your deliverable:\n${toolResult.output.slice(0, 3000)}` },
                    dict.accumulatedOutputs,
                    apiKey
                  );
                  if (!synthesisResult.blocked && synthesisResult.output) {
                    step.output = synthesisResult.output;
                  } else {
                    step.output = combinedOutput;
                  }
                } catch (synthErr: any) {
                  await emitNodeLog(dict, "ToolCall", `Synthesis after tool call failed, keeping raw output: ${synthErr.message}`, { stepId: step.id });
                  step.output = combinedOutput;
                }
              } else {
                step.output = combinedOutput;
              }
            } else {
              await emitNodeLog(dict, "ToolCall", `Tool "${toolResult.toolName}" failed: ${toolResult.error}`, {
                stepId: step.id,
                toolSlug: tc.toolSlug,
                error: toolResult.error,
              });
              step.output = (step.output || "") + `\n\n> Tool "${toolResult.toolName}" failed: ${toolResult.error}`;
            }
          }
        }
      }

      step.status = "completed";
      dict.accumulatedOutputs[step.id] = step.output || "";
      dict.stepResults.push({
        stepId: step.id,
        stepName: step.name,
        output: step.output || "",
        iteration: dict.iteration,
      });

      await emitNodeLog(dict, "ExecStep", `Step "${step.name}" completed`, {
        stepId: step.id,
        outputLength: (step.output || "").length,
        toolsUsed: dict.toolResults.filter(r => r.success).map(r => r.toolSlug),
      });
    } catch (err: any) {
      step.status = "failed";
      step.error = err.message;
      await emitNodeLog(dict, "ExecStep", `Step "${step.name}" failed: ${err.message}`, {
        stepId: step.id,
        error: err.message,
      });
    }
  };

  if (readySteps.length > 1) {
    await emitNodeLog(dict, "ExecStep", `Parallel execution: ${readySteps.length} independent steps`, {
      steps: readySteps.map(s => s.name),
    });
    await Promise.all(readySteps.map(step => executeStep(step)));
  } else {
    await executeStep(readySteps[0]);
  }

  const hasBlocked = dict.planSteps.some(s => s.status === "blocked");
  if (hasBlocked) {
    dict.blocked = true;
    return { action: "bdm" };
  }

  const hasMorePending = dict.planSteps.some(s => s.status === "pending");
  if (hasMorePending) return { action: "more_steps" };

  return { action: "done" };
}

async function nodeEmitBDM(dict: SharedDict): Promise<NodeResult> {
  const partialOutput = Object.values(dict.accumulatedOutputs).join("\n\n---\n\n");
  dict.partialDeliverables = partialOutput ? [partialOutput] : [];

  await emitNodeLog(dict, "EmitBDM", `BDM marker emitted: ${dict.bdmMarker?.reason || "Unknown block"}`, {
    bdmMarker: dict.bdmMarker,
    partialOutputKeys: Object.keys(dict.accumulatedOutputs),
    iteration: dict.iteration,
  });

  return { action: "done" };
}

async function nodeEvaluate(dict: SharedDict): Promise<NodeResult> {
  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);
  const combinedOutput = Object.values(dict.accumulatedOutputs).join("\n\n");

  const failedSteps = dict.planSteps.filter(s => s.status === "failed");
  if (failedSteps.length > 0 && dict.iteration < dict.maxIterations - 1) {
    const failedGaps = failedSteps.map(s => `Step "${s.name}" failed: ${s.error || "unknown error"}`);
    dict.evaluationScore = 0.4;
    dict.evaluationResult = {
      score: 0.4,
      meetsCriteria: false,
      gaps: failedGaps,
      strengths: dict.planSteps.filter(s => s.status === "completed").map(s => `Step "${s.name}" completed`),
      reasoning: `${failedSteps.length} step(s) failed — triggering refinement`,
    };
    await emitNodeLog(dict, "Evaluate", `${failedSteps.length} failed steps detected — forcing refinement`, {
      failedSteps: failedSteps.map(s => s.name),
      score: 0.4,
    });
    return { action: "refine" };
  }

  const completedSteps = dict.planSteps.filter(s => s.status === "completed");
  const allFailed = completedSteps.length === 0 && dict.planSteps.length > 0;

  if (allFailed) {
    dict.evaluationScore = 0.0;
    dict.evaluationResult = {
      score: 0.0,
      meetsCriteria: false,
      gaps: dict.planSteps.map(s => `Step "${s.name}" ${s.status}: ${s.error || "no output"}`),
      strengths: [],
      reasoning: "All steps failed — no deliverable produced",
    };
    await emitNodeLog(dict, "Evaluate", `All ${dict.planSteps.length} steps failed — best effort with empty output`, {
      score: 0.0,
      failedCount: dict.planSteps.length,
    });
    return { action: "best_effort" };
  }

  if (!settings || !combinedOutput) {
    dict.evaluationScore = 1.0;
    dict.evaluationResult = {
      score: 1.0,
      meetsCriteria: true,
      gaps: [],
      strengths: ["Execution completed"],
      reasoning: "Fallback mode — no evaluation needed",
    };
    await emitNodeLog(dict, "Evaluate", `Fallback mode: auto-converged (score=1.0)`, { score: 1.0 });
    return { action: "converged" };
  }

  try {
    const evalResult = await llmEvaluate(
      settings,
      systemPrompt,
      dict.workOrder,
      combinedOutput,
      dict.planSteps,
      apiKey,
      detectRequiredFormat(dict)
    );

    dict.evaluationScore = evalResult.score;
    dict.evaluationResult = evalResult;

    await emitNodeLog(dict, "Evaluate",
      `Quality score: ${evalResult.score.toFixed(2)} | Criteria met: ${evalResult.meetsCriteria} | Gaps: ${evalResult.gaps.length}`,
      { ...evalResult, iteration: dict.iteration }
    );

    if (evalResult.score >= dict.convergenceThreshold && evalResult.meetsCriteria) {
      return { action: "converged" };
    }

    if (dict.iteration >= dict.maxIterations - 1) {
      await emitNodeLog(dict, "Evaluate", `Max iterations (${dict.maxIterations}) reached — delivering best effort`, {
        score: evalResult.score,
      });
      return { action: "best_effort" };
    }

    return { action: "refine" };
  } catch (err: any) {
    dict.evaluationScore = 0.85;
    dict.evaluationResult = {
      score: 0.85,
      meetsCriteria: true,
      gaps: [],
      strengths: ["Execution completed"],
      reasoning: `Evaluation LLM failed (${err.message}), assuming acceptable quality`,
    };
    await emitNodeLog(dict, "Evaluate", `Evaluation LLM failed, auto-converging: ${err.message}`, { error: err.message });
    return { action: "converged" };
  }
}

async function nodeRefine(dict: SharedDict): Promise<NodeResult> {
  const settings = getEffectiveSettings(dict);
  const apiKey = getEffectiveApiKey(dict);
  const systemPrompt = getSystemPrompt(dict);
  const gaps = dict.evaluationResult?.gaps || [];

  if (!settings || gaps.length === 0) {
    await emitNodeLog(dict, "Refine", `No refinable gaps — converging`, { gaps: [] });
    return { action: "converged" };
  }

  try {
    const refinement = await llmRefine(
      settings,
      systemPrompt,
      dict.workOrder,
      gaps,
      dict.accumulatedOutputs,
      dict.planSteps,
      apiKey
    );

    dict.refinementHistory.push({
      iteration: dict.iteration,
      gaps: refinement.gaps,
      deltaSteps: refinement.deltaSteps.map(s => s.name),
    });

    for (const step of dict.planSteps) {
      if (step.status === "failed") {
        step.status = "pending";
        step.error = undefined;
      }
    }

    dict.iteration++;

    await emitNodeLog(dict, "Refine",
      `Refinement iteration ${dict.iteration}: ${refinement.deltaSteps.length} delta steps identified`,
      { gaps: refinement.gaps, deltaSteps: refinement.deltaSteps.map(s => s.name) }
    );

    return { action: "continue" };
  } catch (err: any) {
    await emitNodeLog(dict, "Refine", `Refinement LLM failed, converging with current output: ${err.message}`, { error: err.message });
    return { action: "converged" };
  }
}

function isIntermediateOutput(output: string): boolean {
  const trimmed = output.trim();
  if (trimmed.length < 20) return true;
  if (/^\s*[\[{]/.test(trimmed) && /[\]}]\s*$/.test(trimmed)) {
    try {
      const parsed = JSON.parse(trimmed);
      if (Array.isArray(parsed) || (typeof parsed === "object" && parsed !== null)) {
        const str = JSON.stringify(parsed);
        if (!/<!DOCTYPE|<html|<body|<div|<section|<article/i.test(str)) {
          return true;
        }
      }
    } catch {}
  }
  const metadataPatterns = [
    /^\s*\{?\s*"(title|headlines|sections|layout|structure|wireframe|components)"\s*:/i,
    /^\s*(Step \d+ complete|Planning complete|Research complete|Data gathered)/i,
  ];
  if (metadataPatterns.some(p => p.test(trimmed))) return true;
  return false;
}

function selectBestHtmlOutput(outputs: Record<string, string>): string | null {
  let bestKey: string | null = null;
  let bestScore = -1;
  for (const [key, output] of Object.entries(outputs)) {
    if (!output || output.trim().length < 50) continue;
    let score = 0;
    if (/<!DOCTYPE\s+html/i.test(output)) score += 100;
    if (/<html[\s>]/i.test(output)) score += 80;
    if (/<head[\s>]/i.test(output) && /<body[\s>]/i.test(output)) score += 60;
    if (/<\/html>/i.test(output)) score += 40;
    if (/<meta\s/i.test(output)) score += 10;
    if (/<style[\s>]/i.test(output)) score += 10;
    if (score > bestScore) {
      bestScore = score;
      bestKey = key;
    }
  }
  return bestKey && bestScore >= 80 ? outputs[bestKey] : null;
}

function cleanDeliverable(raw: string): string {
  let cleaned = raw;
  if (/\\n/.test(cleaned) && !/<[a-z]/i.test(cleaned.substring(0, 200))) {
    cleaned = cleaned.replace(/\\n/g, "\n").replace(/\\t/g, "\t").replace(/\\"/g, '"');
  }
  cleaned = cleaned.replace(/^[\s\S]*?(<!DOCTYPE\s+html)/i, "$1");
  if (/<!DOCTYPE\s+html/i.test(cleaned) && /<\/html>/i.test(cleaned)) {
    const endIdx = cleaned.lastIndexOf("</html>") + "</html>".length;
    cleaned = cleaned.substring(0, endIdx);
  }
  return cleaned;
}

/**
 * Detect if the work order deliverable should be a specific file format
 * based on work order description and assigned tool skills.
 */
function detectRequiredFormat(dict: SharedDict): "pptx" | "pdf" | null {
  const text = `${dict.workOrder.title} ${dict.workOrder.description}`.toLowerCase();

  // Explicit keyword matching takes priority over skill-based detection
  const hasPdfKeywords = /\b(pdf|portable\s*document)\b/.test(text);
  if (hasPdfKeywords) return "pdf";

  const hasPptxKeywords = /\b(pptx|powerpoint|slide\s*deck|presentation|pitch\s*deck|slides)\b/.test(text);
  if (hasPptxKeywords) return "pptx";

  // Fall back to skill-based detection
  const hasPptxSkill = dict.availableTools.some(
    t => t.executionMode === "prompt_injection" && /pptx|powerpoint|presentation/i.test(t.slug + " " + t.name)
  );
  if (hasPptxSkill) return "pptx";

  const hasPdfSkill = dict.availableTools.some(
    t => t.executionMode === "prompt_injection" && /pdf/i.test(t.slug + " " + t.name)
  );
  if (hasPdfSkill) return "pdf";

  return null;
}

/**
 * Inject a professional CSS stylesheet into a pandoc-generated HTML document
 * before LibreOffice renders it to PDF.
 */
function injectPdfStyles(html: string, title: string): string {
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const css = `
<style>
  /* ── Page: zero margins — Chromium/Playwright respects this for full-bleed ── */
  @page { margin: 0; }

  /* ── Override pandoc's default narrow body (max-width:36em, margin:auto) ── */
  html, body {
    max-width: none !important;
    width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
    background: #ffffff !important;
  }

  /* ── Base typography ── */
  body {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1a1a1a;
  }

  /* ── Header bar: edge-to-edge, full-bleed ── */
  .doc-header {
    background: #0d1b3e;
    color: #ffffff;
    padding: 18px 25mm 15px 25mm;
    width: 100%;
    box-sizing: border-box;
  }
  .doc-header .doc-eyebrow {
    font-size: 7.5pt;
    letter-spacing: 2px;
    text-transform: uppercase;
    color: #7eb3ff;
    margin-bottom: 5px;
  }
  .doc-header .doc-title {
    font-size: 20pt;
    font-weight: 700;
    color: #ffffff;
    line-height: 1.2;
  }
  .doc-header .doc-subtitle {
    font-size: 9pt;
    color: #a8c4e8;
    margin-top: 5px;
  }

  /* ── Body content area: padding provides page margins ── */
  .doc-body {
    padding: 14mm 25mm 20mm 25mm;
    box-sizing: border-box;
  }

  /* ── Headings ── */
  h1 {
    font-size: 14pt;
    font-weight: 700;
    color: #0d1b3e;
    border-bottom: 2px solid #0d1b3e;
    padding-bottom: 5px;
    margin: 20px 0 10px 0;
  }
  h2 {
    font-size: 10.5pt;
    font-weight: 700;
    color: #1a3a6b;
    margin: 16px 0 6px 0;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  h3 {
    font-size: 10.5pt;
    font-weight: 700;
    color: #2c5282;
    margin: 12px 0 5px 0;
  }

  /* ── Paragraphs ── */
  p { margin: 0 0 9px 0; }

  /* ── Lists ── */
  ul, ol { margin: 5px 0 10px 22px; padding: 0; }
  ul { list-style-type: disc; }
  ol { list-style-type: decimal; }
  li { margin-bottom: 4px; padding-left: 3px; }
  li strong { color: #1a3a6b; }

  /* ── Strong ── */
  strong { font-weight: 700; }

  /* ── HR → section divider ── */
  hr { border: none; border-top: 1px solid #d0dae8; margin: 18px 0; }

  /* ── Callout box ── */
  blockquote {
    background: #eef4ff;
    border-left: 4px solid #1a3a6b;
    padding: 9px 14px;
    margin: 12px 0;
    font-style: normal;
    color: #1a2a4a;
    border-radius: 0 4px 4px 0;
  }

  /* ── Footer: fixed to bottom of every page — Chromium supports position:fixed in print ── */
  .doc-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background: #0d1b3e;
    color: #7eb3ff;
    font-size: 7.5pt;
    padding: 6px 25mm;
    display: flex;
    justify-content: space-between;
    box-sizing: border-box;
  }
  .doc-footer span { line-height: 1.4; }
</style>`;

  // Build header/footer — natural full-width with @page margin: 0
  const headerBlock = `
<div class="doc-header">
  <div class="doc-eyebrow">AIDEN IWO Platform</div>
  <div class="doc-title">${title}</div>
  <div class="doc-subtitle">Confidential &nbsp;|&nbsp; ${today}</div>
</div>
<div class="doc-body">`;

  const footerBlock = `</div>
<div class="doc-footer">
  <span>AIDEN IWO — Confidential</span>
  <span>${today}</span>
</div>`;

  // Inject CSS into <head>, wrap body content
  let result = html;
  result = result.replace(/<\/head>/, `${css}\n</head>`);

  // Remove pandoc's title block — pandoc wraps the metadata title in:
  //   <header id="title-block-header"><h1 class="title">...</h1></header>
  // This duplicates our header bar, so strip it entirely.
  result = result.replace(
    /<body[^>]*>([\s\S]*?)<\/body>/i,
    (_match: string, bodyContent: string) => {
      let stripped = bodyContent
        // Strip pandoc's title-block header element
        .replace(/<header[^>]*id=["']title-block-header["'][^>]*>[\s\S]*?<\/header>\s*/i, "")
        // Fallback: strip any lone leading H1 (single-line — covers simple cases)
        .replace(/^\s*<h1[^>]*>[^<]*<\/h1>\s*/i, "");
      return `<body>\n${headerBlock}\n${stripped}\n${footerBlock}\n</body>`;
    }
  );

  return result;
}

/**
 * Post-process the deliverable: convert markdown to the required output format.
 * Currently supports markdown → .pptx conversion via python-pptx.
 */
async function nodePostProcess(dict: SharedDict): Promise<void> {
  const format = detectRequiredFormat(dict);
  if (!format) return;

  if (format === "pptx") {
    try {
      // Detect whether the sub-agent produced HTML slides or markdown
      const deliverable = dict.finalDeliverable;
      const isHtmlSlides = /<section[^>]*class=["'][^"']*slide[^"']*["']/i.test(deliverable.slice(0, 1000)) ||
        (/<!DOCTYPE html|<html/i.test(deliverable.slice(0, 200)) && /<section/i.test(deliverable));

      const scriptPath = isHtmlSlides
        ? path.resolve(process.cwd(), "server/scripts/html-to-pptx.cjs")
        : path.resolve(process.cwd(), "server/scripts/md-to-pptx.py");

      if (!fs.existsSync(scriptPath)) {
        await emitNodeLog(dict, "PostProcess", "PPTX conversion script not found — skipping", { scriptPath });
        return;
      }

      // Write deliverable to temp file
      const tmpDir = path.resolve(".local/tmp");
      fs.mkdirSync(tmpDir, { recursive: true });
      const ext = isHtmlSlides ? "html" : "md";
      const inputPath = path.join(tmpDir, `${dict.workOrder.id}.${ext}`);
      const outputPath = path.join(tmpDir, `${dict.workOrder.id}.pptx`);
      fs.writeFileSync(inputPath, dict.finalDeliverable, "utf-8");

      // Run conversion (html2pptx needs more time — Playwright launches a browser per slide)
      const title = dict.deliverableTitle || dict.workOrder.title;
      const cmd = isHtmlSlides
        ? `node "${scriptPath}" --input "${inputPath}" --output "${outputPath}"`
        : `python3 "${scriptPath}" --input "${inputPath}" --output "${outputPath}" --title "${title.replace(/"/g, '\\"')}"`;

      await emitNodeLog(dict, "PostProcess", `Converting deliverable to PPTX via ${isHtmlSlides ? "html2pptx" : "md-to-pptx"}`, { isHtmlSlides });

      const result = execSync(cmd, { timeout: isHtmlSlides ? 90000 : 30000, encoding: "utf-8" });

      const parsed = JSON.parse(result.trim());
      if (parsed.success && fs.existsSync(outputPath)) {
        const stats = fs.statSync(outputPath);
        dict.postProcessedFile = {
          path: outputPath,
          mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          size: stats.size,
        };

        // Update the deliverable message to note the file was generated
        dict.finalMessage += ` A .pptx file (${parsed.slideCount} slides, ${(stats.size / 1024).toFixed(0)}KB) has been generated.`;

        await emitNodeLog(dict, "PostProcess", `PPTX generated: ${parsed.slideCount} slides, ${(stats.size / 1024).toFixed(0)}KB`, {
          format: "pptx",
          slideCount: parsed.slideCount,
          fileSize: stats.size,
          path: outputPath,
        });
      }

      // Clean up input temp file
      fs.unlinkSync(inputPath);
    } catch (err: any) {
      await emitNodeLog(dict, "PostProcess", `PPTX conversion failed: ${err.message}`, { error: err.message });
    }
  }

  if (format === "pdf") {
    try {
      const tmpDir = path.resolve(".local/tmp");
      fs.mkdirSync(tmpDir, { recursive: true });

      const title = (dict.deliverableTitle || dict.workOrder.title).replace(/"/g, '\\"');
      const mdPath = path.join(tmpDir, `${dict.workOrder.id}.md`);
      const htmlPath = path.join(tmpDir, `${dict.workOrder.id}.html`);
      const pdfPath = path.join(tmpDir, `${dict.workOrder.id}.pdf`);

      fs.writeFileSync(mdPath, dict.finalDeliverable, "utf-8");

      await emitNodeLog(dict, "PostProcess", "Converting deliverable to PDF via pandoc + Playwright Chromium");

      // Step 1: markdown → standalone HTML (pandoc handles markdown reliably)
      execSync(
        `pandoc "${mdPath}" -t html5 --standalone --metadata title="${title}" -o "${htmlPath}"`,
        { timeout: 30000, encoding: "utf-8" }
      );

      if (!fs.existsSync(htmlPath)) {
        throw new Error("pandoc failed to produce HTML intermediate file");
      }

      // Step 1b: Inject professional CSS + header/footer layout
      const rawHtml = fs.readFileSync(htmlPath, "utf-8");
      const styledHtml = injectPdfStyles(rawHtml, dict.deliverableTitle || dict.workOrder.title);
      fs.writeFileSync(htmlPath, styledHtml, "utf-8");

      // Step 2: HTML → PDF via Playwright Chromium (full CSS support: position:fixed, @page, full-bleed)
      const pdfScriptPath = path.resolve(process.cwd(), "server/scripts/html-to-pdf.cjs");
      const pdfResult = execSync(
        `node "${pdfScriptPath}" --input "${htmlPath}" --output "${pdfPath}"`,
        { timeout: 60000, encoding: "utf-8" }
      );

      let pdfScriptOutput: any = {};
      try { pdfScriptOutput = JSON.parse(pdfResult.trim()); } catch { /* non-JSON stderr mixed in */ }

      if (!fs.existsSync(pdfPath) || !pdfScriptOutput.success) {
        throw new Error(`Playwright PDF conversion failed: ${pdfScriptOutput.error || "no output file"}`);
      }

      const stats = fs.statSync(pdfPath);

      // Move PDF to workspace artifacts directory
      const safeTitle = (dict.deliverableTitle || dict.workOrder.title)
        .replace(/[^a-z0-9_\-\s]/gi, "")
        .trim()
        .replace(/\s+/g, "_")
        .slice(0, 60);
      const artifactDir = path.resolve(".local/workspace/05_Artifacts");
      fs.mkdirSync(artifactDir, { recursive: true });
      const finalPdfPath = path.join(artifactDir, `${safeTitle}.pdf`);
      fs.copyFileSync(pdfPath, finalPdfPath);

      dict.postProcessedFile = {
        path: finalPdfPath,
        mimeType: "application/pdf",
        size: stats.size,
      };

      dict.finalMessage += ` A PDF document (${(stats.size / 1024).toFixed(0)}KB) has been generated.`;

      await emitNodeLog(dict, "PostProcess", `PDF generated: ${(stats.size / 1024).toFixed(0)}KB`, {
        format: "pdf",
        fileSize: stats.size,
        path: finalPdfPath,
      });

      // Clean up temp files
      fs.unlinkSync(mdPath);
      fs.unlinkSync(htmlPath);
      fs.unlinkSync(pdfPath);
    } catch (err: any) {
      await emitNodeLog(dict, "PostProcess", `PDF conversion failed: ${err.message}`, { error: err.message });
    }
  }
}

async function nodeBuildResponse(dict: SharedDict): Promise<NodeResult> {
  const orderText = `${dict.workOrder.title} ${dict.workOrder.description}`.toLowerCase();
  // BUG-011 fix: PPTX-bound or PDF-bound work orders must never be routed to HTML assembly,
  // even if "sandbox" or another HTML-adjacent keyword appears in the order text.
  const detectedFormat = detectRequiredFormat(dict);
  const requiresPptx = detectedFormat === "pptx";
  const requiresPdf = detectedFormat === "pdf";
  const expectsHtml = !requiresPptx && !requiresPdf && (
    /\b(html|web\s*page|landing\s*page|homepage|website|web\s*app|dashboard\s*page|interactive\s*page)\b/i.test(orderText) ||
    (/sandbox/i.test(orderText))
  );

  let combinedDeliverable: string;

  if (requiresPdf) {
    // For PDF: use only the most recent completed step output — never concatenate iterations.
    // Multiple iteration outputs of the same document create duplicate pages.
    const lastStepOutput = dict.stepResults.length > 0
      ? dict.stepResults[dict.stepResults.length - 1].output
      : null;
    const fallbackValues = Object.values(dict.accumulatedOutputs);
    combinedDeliverable = lastStepOutput
      ? cleanDeliverable(lastStepOutput)
      : fallbackValues.length > 0 ? cleanDeliverable(fallbackValues[fallbackValues.length - 1]) : "";
  } else if (expectsHtml) {
    const bestHtml = selectBestHtmlOutput(dict.accumulatedOutputs);
    if (bestHtml) {
      combinedDeliverable = cleanDeliverable(bestHtml);
    } else {
      const contentOutputs = Object.entries(dict.accumulatedOutputs)
        .filter(([_, v]) => !isIntermediateOutput(v))
        .map(([_, v]) => v);
      combinedDeliverable = contentOutputs.length > 0
        ? cleanDeliverable(contentOutputs.join("\n\n"))
        : Object.values(dict.accumulatedOutputs).join("\n\n");
    }
  } else {
    // BUG-025 fix: Use only the last iteration's step outputs to prevent content duplication.
    // On refinement loops, new steps get new IDs — all iterations accumulate in accumulatedOutputs.
    // Joining across iterations produces duplicate full-document content.
    const lastIterResults = dict.stepResults.filter(r => r.iteration === dict.iteration);
    const targetResults = lastIterResults.length > 0 ? lastIterResults : dict.stepResults;
    const contentOutputs = targetResults
      .filter(r => !isIntermediateOutput(r.output))
      .map(r => r.output);
    combinedDeliverable = contentOutputs.length > 0
      ? contentOutputs.join("\n\n")
      : Object.values(dict.accumulatedOutputs).filter(v => !isIntermediateOutput(v)).join("\n\n")
        || Object.values(dict.accumulatedOutputs).join("\n\n");
  }

  if (!combinedDeliverable.trim() && dict.stepResults.length === 0) {
    combinedDeliverable = generateFallbackDeliverable(dict.workOrder);
  }

  const typeToDeliverableType: Record<string, "document" | "code" | "image" | "mixed"> = {
    deployment: "document",
    maintenance: "document",
    incident: "document",
    change_request: "document",
    security: "document",
    configuration: "code",
    standard: "document",
  };

  dict.finalDeliverable = combinedDeliverable;
  dict.finalMessage = `Work order "${dict.workOrder.title}" processed successfully.`;
  let detectedType = typeToDeliverableType[dict.workOrder.type] || "document";
  const codeBlockMatches = combinedDeliverable.match(/```(html|javascript|js|css)\b[\s\S]*?```/gi) || [];
  const totalCodeLength = codeBlockMatches.reduce((sum, m) => sum + m.length, 0);
  if (totalCodeLength > 200 || /<!DOCTYPE\s+html|<html[\s>]/i.test(combinedDeliverable)) {
    detectedType = "code";
  }
  dict.deliverableType = detectedType;
  dict.deliverableTitle = dict.workOrder.title;

  if (dict.stepResults.length > 0) {
    const lastResult = dict.stepResults[dict.stepResults.length - 1];
    if (lastResult.output) {
      dict.finalDeliverable = combinedDeliverable;
    }
  }

  await emitNodeLog(dict, "BuildResponse",
    `Final deliverable assembled | Score: ${dict.evaluationScore.toFixed(2)} | Iterations: ${dict.iteration + 1} | Steps: ${dict.stepResults.length}`,
    {
      score: dict.evaluationScore,
      iterations: dict.iteration + 1,
      totalSteps: dict.stepResults.length,
      deliverableLength: dict.finalDeliverable.length,
      deliverableType: dict.deliverableType,
    }
  );

  return { action: "done" };
}

export async function pocketflowExecute(
  order: WorkOrder,
  tier1Result: Tier1Result,
  llmConfig: EffectiveLlmConfig | null,
  settings: LlmSettings | null,
  options?: { maxIterations?: number; convergenceThreshold?: number; revisionContext?: string }
): Promise<Tier2Result> {
  const dict = createSharedDict(
    order,
    tier1Result,
    llmConfig,
    settings,
    options?.maxIterations ?? 3,
    options?.convergenceThreshold ?? 0.8
  );

  if (options?.revisionContext) {
    dict.revisionContext = options.revisionContext;
  }

  try {
    const tools = await getAvailableToolsForAgent(order.assignedSubAgentId || undefined);
    dict.availableTools = tools;
  } catch (err: any) {
    console.error("Failed to load available tools:", err.message);
  }

  await emitNodeLog(dict, "PocketFlow", `Starting iterative execution for "${order.title}"`, {
    maxIterations: dict.maxIterations,
    convergenceThreshold: dict.convergenceThreshold,
    hasLLM: !!llmConfig || !!settings?.enabled,
    availableTools: dict.availableTools.map(t => t.slug),
  });

  const validateResult = await nodeValidateWorkOrder(dict);
  if (validateResult.action === "bdm") {
    await nodeEmitBDM(dict);
    return buildBlockedResult(dict);
  }

  const planResult = await nodePlanSteps(dict);
  if (planResult.action === "bdm") {
    await nodeEmitBDM(dict);
    return buildBlockedResult(dict);
  }

  while (dict.iteration < dict.maxIterations) {
    let execAction: NodeAction = "more_steps";
    while (execAction === "more_steps") {
      const execResult = await nodeExecStep(dict);
      execAction = execResult.action;

      if (execAction === "bdm") {
        await nodeEmitBDM(dict);
        return buildBlockedResult(dict);
      }
    }

    const evalResult = await nodeEvaluate(dict);

    if (evalResult.action === "converged" || evalResult.action === "best_effort") {
      await nodeBuildResponse(dict);
      await nodePostProcess(dict);
      return buildSuccessResult(dict);
    }

    if (evalResult.action === "refine") {
      const refineResult = await nodeRefine(dict);
      if (refineResult.action === "converged") {
        await nodeBuildResponse(dict);
        await nodePostProcess(dict);
        return buildSuccessResult(dict);
      }

      const rePlanResult = await nodePlanSteps(dict);
      if (rePlanResult.action === "bdm") {
        await nodeEmitBDM(dict);
        return buildBlockedResult(dict);
      }
    }
  }

  await emitNodeLog(dict, "PocketFlow", `Iteration limit reached — delivering best effort`, {
    iterations: dict.iteration,
    score: dict.evaluationScore,
  });
  await nodeBuildResponse(dict);
  await nodePostProcess(dict);
  return buildSuccessResult(dict);
}

function buildBlockedResult(dict: SharedDict): Tier2Result {
  const partialOutput = dict.partialDeliverables.length > 0
    ? dict.partialDeliverables.join("\n\n---\n\n")
    : undefined;

  return {
    blocked: true,
    reason: dict.bdmMarker?.reason || "Execution blocked",
    executionId: null,
    handler: dict.tier1Result.handler,
    output: partialOutput ? {
      message: "Partial output available before block",
      deliverable: partialOutput,
      deliverableType: "document",
      deliverableTitle: `${dict.workOrder.title} (partial)`,
    } : undefined,
    pocketflow: {
      iterations: dict.iteration + 1,
      convergenceScore: dict.evaluationScore,
      stepResults: dict.stepResults,
      refinementHistory: dict.refinementHistory,
      bdmMarker: dict.bdmMarker,
    },
  };
}

function buildSuccessResult(dict: SharedDict): Tier2Result {
  const toolsUsed = dict.toolResults.filter(r => r.success).map(r => ({
    slug: r.toolSlug,
    name: r.toolName,
    durationMs: r.durationMs,
    leaseId: r.leaseId,
  }));

  return {
    blocked: false,
    reason: null,
    executionId: `exec_${Date.now()}`,
    handler: dict.tier1Result.handler,
    output: {
      message: dict.finalMessage,
      deliverable: dict.finalDeliverable,
      deliverableType: dict.deliverableType,
      deliverableTitle: dict.deliverableTitle,
      postProcessedFile: dict.postProcessedFile || undefined,
    },
    pocketflow: {
      iterations: dict.iteration + 1,
      convergenceScore: dict.evaluationScore,
      stepResults: dict.stepResults,
      refinementHistory: dict.refinementHistory,
      toolsUsed: toolsUsed.length > 0 ? toolsUsed : undefined,
    },
  };
}
